Feature/signup
vinhduong2412/todoList pull request #2
Opened 2022-11-23 07:20 UTC by vinhduong2412

2022-11-24 03:30 UTC, mvn-dungdang-hn commented on .gitignore
> +bin
```suggestion
bin

```

2022-11-24 03:31 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountController.cs
> +    public class AccountController : ControllerBase
```suggestion
    public class AccountsController : ControllerBase
```
tên controller trong .net là số nhiều nhé

2022-11-24 03:32 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountController.cs
> +namespace todo.Controllers
```suggestion
namespace ToDo.Controllers
```
convention cho namespace là dạng CamelCase nhé

2022-11-24 03:33 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountController.cs
> +        private readonly IAccountRepo accountRepo;
```suggestion
        private readonly IAccountService accountService;
```

2022-11-24 03:34 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountController.cs
> +        [HttpPost("SignUp")]
đọc lại giúp a về Restful API nhé

2022-11-24 03:35 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountController.cs
> +        [HttpPost("SignUp")]
rồi sửa lại cả những chỗ tương tự nhé

2022-11-24 03:35 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountController.cs
> +        public async Task<IActionResult> SignUp([FromBody]SignUpModel model)
```suggestion
        public async Task<IActionResult> SignUp([FromBody]SignUpModel input)
```

2022-11-24 03:35 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountController.cs
> +        public async Task<ActionResult> SignIn([FromBody] SignInModel model)
```suggestion
        public async Task<ActionResult> SignIn([FromBody] SignInModel input)
```

2022-11-24 03:38 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountController.cs
> +
thiếu [Route] vs [ApiController] attribute

2022-11-24 03:38 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +        private readonly ITaskRepo _taskRepo;
```suggestion
        private readonly ITaskService _taskService;
```

2022-11-24 04:17 UTC, mvn-dungdang-hn requested changes

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +        private object _mapper;
cái này là gì nhỉ ?

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +        public async Task<IActionResult> GetAlltodoTasks()
```suggestion
        public async Task<IActionResult> GetAllTodoTasks()
```

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +                return Ok(await _taskRepo.GetAlltodoTasksAsync());
```suggestion
                return Ok(await _taskRepo.GetAllTodoTasksAsync());
```

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +            var task = await _taskRepo.GettodoTasksAsync(id);
```suggestion
            var task = await _taskRepo.GetTodoTasksAsync(id);
```

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +                var newTaskId = await _taskRepo.AddtodoTaskAsync(model);
```suggestion
                var newTaskId = await _taskRepo.AddTodoTaskAsync(model);
```

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +                var task = await _taskRepo.GettodoTasksAsync(newTaskId);
bên trên nên trả về task luôn thì k cần dòng mới này để lấy task vừa tạo

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +        public async Task<IActionResult> PostTask(todoTaskModel model)
```suggestion
        public async Task<IActionResult> PostTask(todoTaskModel input)
```

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +        public async Task<IActionResult> PutTask(int id, [FromBody] todoTaskModel model)
```suggestion
        public async Task<IActionResult> PutTask(int id, [FromBody] TodoTaskModel input)
```

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Models/SignInModel.cs
> +﻿using System.ComponentModel.DataAnnotations;
cái này để tên thư mục và namespace giúp là DTOs nhé

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Models/SignInModel.cs
> +    public class SignInModel
```suggestion
    public class SignInInput
```

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Models/SignUpModel.cs
> +    public class SignUpModel
```suggestion
    public class SignUpInput
```

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Models/SignUpModel.cs
> +        public string ConfirmPassword { get; set; } = null!;
cái này k cần nhé. ConfirmPassword sẽ được làm ở phía FE

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Models/SignUpModel.cs
> +        public string FirstName { get; set; } = null!;
sao lại cần `null!` làm gì nhỉ

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Models/SignUpModel.cs
> +namespace todo.Models
```suggestion
namespace Todo.Models
```

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +    public class todoTasksController : ControllerBase
sao lại vừa có Tasks rồi lại còn TodoTasks Controller thế nhỉ ?

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Data/Category.cs
> +﻿using System.ComponentModel.DataAnnotations;
đổi lại tên folder và namespace thành Models nhé

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Data/Category.cs
> +    [Table("Category")]
tên table sẽ là số nhiều nhé

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Data/Category.cs
> +    [Table("Category")]
```suggestion
    [Table("Categories")]
```

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Repositories/TaskRepo.cs
> +            var deleteTask = _context.todoTasks!.SingleOrDefault(t => t.Id == id);
sao cứ phải thêm ! vào làm gì thế ?

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Repositories/TaskRepo.cs
> +            var deleteTask = _context.todoTasks!.SingleOrDefault(t => t.Id == id);
```suggestion
            var deleteTask = await _context.todoTasks!.FirstOrDefaultAsync(t => t.Id == id);
```

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Repositories/TaskRepo.cs
> +﻿using AutoMapper;
sửa hết Repo thành Service nhé

2022-11-24 04:17 UTC, mvn-dungdang-hn commented on todo/Repositories/TaskRepo.cs
> +﻿using AutoMapper;
toàn bộ return của method trong 1 service thì trả về DTO nhé chứ k trả trực tiếp cho Model

2022-11-24 04:18 UTC, mvn-dungdang-hn commented on todo/Program.cs
> +builder.Services.AddControllers();
chưa có config cho log

2022-11-25 06:30 UTC, vinhduong2412 commented on todo/Repositories/TaskRepo.cs
> +            var deleteTask = _context.todoTasks!.SingleOrDefault(t => t.Id == id);
cái này em thấy cho vào thì nó không báo warning có thể null nữa

2022-11-29 02:02 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountsController.cs
> +        private readonly IAccountService accountRepo;
```suggestion
        private readonly IAccountService accountService;
```
sửa thì nhớ sửa hết nhé

2022-11-29 02:05 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountsController.cs
> +        public AccountsController(IAccountService repo)
```suggestion
        public AccountsController(IAccountService accountService)
```

2022-11-29 02:06 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountsController.cs
> +            accountRepo = repo;
```suggestion
            _accountService = accountService;
```

2022-11-29 02:07 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountsController.cs
> +            accountRepo = repo;
sửa cả những chỗ tương tự thế này nhé

2022-11-29 02:09 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +
```suggestion
```

2022-11-29 02:10 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +                return BadRequest();
ở đây return internal server error nhé

2022-11-29 02:11 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +                return BadRequest();
BadRequest chỉ trả về khi dữ liệu truyền lên k hợp lệ

2022-11-29 02:17 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +                return newTaskId == null ? NotFound() : Ok(newTaskId);
tạo mới record thì k trả về NotFound nhé. NotFound chỉ trả về khi đường dẫn k tồn tại thôi

2022-11-29 02:18 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +                return NotFound();
```suggestion
                return BadRequest();    
```

2022-11-29 02:18 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +            return Ok("Update successfully");
ở đây nên trả về task đã được update

2022-11-29 02:19 UTC, mvn-dungdang-hn commented on todo/Controllers/TasksController.cs
> +            return Ok("Update successfully");
e sửa cả API ở bên dưới nữa nhé

2022-11-29 02:20 UTC, mvn-dungdang-hn commented on todo/DTOs/todoTaskDTO.cs
> +    public class todoTaskDTO
```suggestion
    public class TodoTaskDTO
```
sửa cả tên file nữa nhé

2022-11-29 02:20 UTC, mvn-dungdang-hn commented on todo/DTOs/todoTaskDTO.cs
> +        public string? Title { get; set; }
```suggestion
        public string Title { get; set; }
```
string k cần ? nhé

2022-11-29 02:22 UTC, mvn-dungdang-hn commented on todo/Models/DataAccessContext.cs
> +        public DbSet<todoTask>? todoTasks { get; set; }
```suggestion
        public DbSet<Task> Tasks { get; set; }
```

2022-11-29 02:22 UTC, mvn-dungdang-hn commented on todo/Models/DataAccessContext.cs
> +        public DbSet<Category>? categories { get; set; }
```suggestion
        public DbSet<Category> categories { get; set; }
```

2022-11-29 02:23 UTC, mvn-dungdang-hn commented on todo/Models/User.cs
> +        public string FirstName { get; set; } = null!;
```suggestion
        public string FirstName { get; set; };
```

2022-11-29 02:23 UTC, mvn-dungdang-hn commented on todo/Models/User.cs
> +
```suggestion
        public string FirstName { get; set; }
        public string LastName { get; set; }
```

2022-11-29 02:25 UTC, mvn-dungdang-hn commented on todo/Models/User.cs
> +
chỗ này a nghĩ thêm [Required]

2022-11-29 02:29 UTC, mvn-dungdang-hn commented on todo/Services/IAccountService.cs
> +        public Task<string> SignInAsync(SignInDTO model);
```suggestion
        Task<ActionResult<SignUpDTO>> SignUpAsync(SignUpDTO model);
        Task<string> SignInAsync(SignInDTO model);
```
interface thì k cần cái này nhé

2022-11-29 02:32 UTC, mvn-dungdang-hn commented on todo/Services/TaskService.cs
> +            return newTask.Id;
chỗ này trả luôn về object task được tạo mới luôn

2022-11-29 02:34 UTC, mvn-dungdang-hn commented on todo/Services/TaskService.cs
> +            var deleteTask = _context.todoTasks!.SingleOrDefault(t => t.Id == id);
dùng async await vs FindAsync nhé

2022-11-29 02:38 UTC, mvn-dungdang-hn commented on todo/appsettings.Development.json
> +      "Default": "Information",
```suggestion
      "Default": "Debug",
```
Develop thì nên để Debug hết nhé

2022-11-29 02:38 UTC, mvn-dungdang-hn commented on todo/appsettings.Development.json
> +      "Microsoft.AspNetCore": "Warning"
```suggestion
      "Microsoft.AspNetCore": "Debug"
```

2022-11-29 02:41 UTC, mvn-dungdang-hn commented on todo/Program.cs
> +app.Run();
```suggestion
app.Run();

```
cuối file lúc nào cx có 1 blank line nhé

2022-11-29 02:42 UTC, mvn-dungdang-hn commented on todo/Services/ITaskService.cs
> +        public Task DeleteTodoTaskAsync(int id);
```suggestion
        Task<List<todoTaskDTO>> GetAllTodoTasksAsync();
        Task<todoTaskDTO> GetTodoTasksAsync(int id);
        Task<int> AddTodoTaskAsync(todoTask model);
        Task UpdateTodoTaskAsync(int id, todoTask model);
        Task DeleteTodoTaskAsync(int id);
```

2022-12-15 09:15 UTC, mvn-dungdang-hn requested changes

2022-12-15 09:15 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +    public class todoTasksController : ControllerBase
```suggestion
    public class TodoTasksController : ControllerBase
```

2022-12-15 09:15 UTC, mvn-dungdang-hn commented on todo/Controllers/CategoriesController.cs
> +        public async Task<IActionResult> getCategory()
```suggestion
        public async Task<IActionResult> GetCategory()
```

2022-12-15 09:15 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +        public async Task<IActionResult> PutTask(int id, [FromBody] TodoTask input)
```suggestion
        public async Task<IActionResult> PutTask(int id, [FromBody] TodoTask input)
```
sửa lại toàn bộ IActionResult thành ActionResult<{ResponseDTO}> nhé
dùng thế này swagger k gen ra response body được

2022-12-15 09:15 UTC, mvn-dungdang-hn commented on todo/Models/User.cs
> +        public ICollection<TodoTask> todoTasks { get; set; }
```suggestion
        public ICollection<TodoTask> TodoTasks { get; set; }
```

2022-12-15 09:15 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +            var task = await _context.TodoTasks!.ToListAsync();
```suggestion
            var task = await _context.TodoTasks!.ToListAsync();
```
sao vẫn để ! ở đây nhỉ ?

2022-12-16 08:50 UTC, mvn-dungdang-hn requested changes

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Controllers/CategoriesController.cs
> +                return Ok(await _categoryService.GetCategory());
API này chưa có ResponseDTO cho Category

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Controllers/CategoriesController.cs
> +                return StatusCode(500);
```suggestion
                return InternalServerError();
```
nên log lại lỗi nữa nhé, k log lại đến lúc k biết debug kiểu gì đâu

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +            return task == null ? BadRequest() : Ok(task);
null thì trả về NotFound vì đường dẫn k tồn tại chứ k phải BadRequest

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +            await _todoTaskService.DeleteTodoTaskAsync(id);
check trường hợp task k tồn tại thì trả về 404 nhé

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +        }
gộp 2 API này vào API GetAllTasks với query params

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +        public async Task<IActionResult> GetTaskById(int id)
chỗ này chưa sửa swagger

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +        public async Task<IActionResult> GetAllTodoTasks()
chưa sửa swagger

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Models/todoTask.cs
> +    [Table("todoTasks")]
```suggestion
    [Table("TodoTasks")]
```

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Models/todoTask.cs
> +        [ForeignKey("Users")]
```suggestion
        [ForeignKey("Categories")]
        public int CategoryId { get; set; }
        [ForeignKey("Users")]   
        public int UserId { get; set; }
```

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Services/CategoryService.cs
> +            var task = await _context.Categories!.ToListAsync();
```suggestion
            var task = await _context.Categories.ToListAsync();
```

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +    public class todoTaskService : ITodoTaskService
```suggestion
    public class TodoTaskService : ITodoTaskService
```

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Services/ICategoryService.cs
> +        Task<List<CategoryRequestDTO>> GetCategory();
```suggestion
        Task<List<CategoryRequestDTO>> GetCategories();
```

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +                return response;
```suggestion
                _context.TodoTasks.Update(updateTask);
                await _context.SaveChangesAsync();
                return _mapper.Map<TodoTaskResponseDTO>(updateTask);
```

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +            }
```suggestion
            var Task = await _context.TodoTasks.Where(t 
                => t.Status == Status).ToListAsync();
            if (Task == null)
            {
                return null;
            }
            return _mapper.Map<List<TodoTaskResponseDTO>>(Task);
```

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +            return response;
```suggestion
            var Task = await _context.TodoTasks.Where(t => t.Date == Date).ToListAsync();
            if (Task == null)
            {
                return null;
            }
            return _mapper.Map<List<TodoTaskResponseDTO>>(Task);
```

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +            return response;
```suggestion
            var newTask = _mapper.Map<TodoTask>(model);
            _context.TodoTasks.Add(newTask);
            await _context.SaveChangesAsync();
            return _mapper.Map<TodoTaskResponseDTO>(newTask);
```

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +            var deleteTask = await _context.TodoTasks.FindAsync(id);
chỗ này nếu null thì return nulll

2022-12-16 08:50 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountsController.cs
> +    [ApiController]
e làm Signin rồi tất cả các API thêm [Authorize] vào nhé trừ sign up vs login
các API liên quan đến task thì phải xử lý theo đúng user đang đăng nhập

2022-12-22 03:39 UTC, mvn-dungdang-hn commented on todo/Services/ITodoTaskService.cs
> +        public Task<List<TodoTask>> GetTodoTasksAsync(string UserId, FilterRequestDTO model);
```suggestion
        Task<List<TodoTask>> GetTodoTasksAsync(string UserId, FilterRequestDTO model);
```
bỏ public đi nhé

2022-12-22 03:42 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +    public class todoTaskService : ITodoTaskService
cái này chưa sửa

2022-12-22 03:44 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +            }
k có thì return null nhé

2022-12-22 03:44 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +            }
để bên controller check null trả về NotFound

2022-12-22 03:45 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +        public async Task<List<TodoTask>> GetTodoTasksAsync(string UserId, FilterRequestDTO model)
```suggestion
        public async Task<List<TodoTask>> GetTodoTasksAsync(string UserId, FilterRequestDTO queryParams)
```

2022-12-22 03:47 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +                return await query.ToListAsync();
```suggestion
                return await query.ToListAsync();
```
chưa return ở đây nhé.  vì có thể filter theo nhiều điều kiện 1 lúc

2022-12-22 03:47 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +                return await query.ToListAsync();
```suggestion
                return await query.ToListAsync();
```
tương tự như ở trên

2022-12-22 03:47 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +            else
k cần else ở chỗ này

2022-12-22 03:49 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +                var updateTask = await _context.TodoTasks.FirstOrDefaultAsync(c
updateTask == null thì sao ?

2022-12-22 03:59 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountsController.cs
> +            return Ok(newUser);
sao k map sang UserResponseDTO nữa nhỉ ?

2022-12-22 04:09 UTC, mvn-dungdang-hn requested changes

2022-12-22 04:09 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountsController.cs
> +            return Ok(newUser);
cả API bên dưới nữa

2022-12-22 04:09 UTC, mvn-dungdang-hn commented on todo/Controllers/AccountsController.cs
> +        public async Task<IActionResult> SignUp([FromBody] SignUpRequestDTO input)
sửa lại IActionResult để swagger được gen ra đúng với response của API

2022-12-22 04:09 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +            var UserId = HttpContext.User.Claims.Where(c
chỗ này e viết thành extension method nhé

2022-12-22 04:09 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +                return NotFound(new ErrorResponse("Task id not found"));
chỗ này trả về BadRequest()

2022-12-22 04:09 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +            await _todoTaskService.DeleteTodoTaskAsync(UserId, id);
method này nếu k tìm thấy Task thì sẽ return null, còn controller return 404

2022-12-22 04:09 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +            var UserId = HttpContext.User.Claims.Where(c
```suggestion
            var userId = HttpContext.User.Claims.Where(c
```

2022-12-22 04:16 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +        public async Task<IActionResult> GetTaskById(int id)
cả API trên nữa

2022-12-22 04:18 UTC, mvn-dungdang-hn commented on todo/Models/todoTask.cs
> +
```suggestion
```

2022-12-22 04:18 UTC, mvn-dungdang-hn commented on todo/Models/todoTask.cs
> +        public string? Id { get; set; }
```suggestion
        public Guid UserId { get; set; }
```

2022-12-22 04:19 UTC, mvn-dungdang-hn commented on todo/Services/ICategoryService.cs
> +        Task<List<CategoryRequestDTO>> GetCategory();
chỗ này e chưa sửa

2022-12-26 03:45 UTC, mvn-dungdang-hn commented on todo/Models/Category.cs
> +        public virtual ICollection<TodoTask> todoTasks { get; set; }
```suggestion
        public virtual ICollection<TodoTask> TodoTasks { get; set; }
```

2022-12-26 03:45 UTC, mvn-dungdang-hn commented on todo/Models/todoTask.cs
> +        public Guid? Id { get; set; }
```suggestion
        public Guid? UserId { get; set; }
```

2022-12-26 03:45 UTC, mvn-dungdang-hn commented on todo/Models/todoTask.cs
> +    [Table("todoTasks")]
e sửa lại tên file nữa nhé

2022-12-26 03:45 UTC, mvn-dungdang-hn commented on todo/Services/ITodoTaskService.cs
> +        Task <TodoTaskResponseDTO>DeleteTodoTaskAsync(Guid userId, int id);
```suggestion
        Task<TodoTaskResponseDTO> DeleteTodoTaskAsync(Guid userId, int id);
```

2022-12-26 03:45 UTC, mvn-dungdang-hn commented on todo/Services/TodoTaskService.cs
> +        public async Task<List<TodoTask>> GetTodoTasksAsync(Guid userId, FilterRequestDTO queryParams)
map lại sang TodoTaskResponseDTO nhé

2022-12-26 03:45 UTC, mvn-dungdang-hn commented on todo/Controllers/todoTasksController.cs
> +                _logger.LogWarning("Task not found");
```suggestion
                _logger.Information("Task not found");
```

2022-12-27 09:45 UTC, merged